version: '3'



services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: TesloDb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data